### ISSUE TITLE
(with HTML: %charCountHTML%)

### ISSUE THREAD

**Issue by JeremyCanfield** [w8tcha/CKEditor-WordCount-Plugin#110]
When making the following revisions to the CKEditor config.js file or the wordcount plugin.js file, this strange string of code is showing at the bottom right-hand corner of the CKEditor: (with HTML: %charCountHTML%)

```javascript
//Default Config
var defaultConfig = {
  showParagraphs: false,
  showWordCount: false,
  showCharCount: true,
  countSpacesAsChars: true,
  countHTML: true,
  hardLimit: true,

  //MAXLENGTH Properties
  maxWordCount: -1, //negative one means unlimited
  maxCharCount: 8000,

  et cetera . . .
};
```
![strange characters](http://www.trojanbot.com/uploads/ckeditor_charcount_chili.png)

In the plugin.js file is this segment of code.

```javascript
if (config.ShowCharCount) {
  var charLabel = editor.lang.wordcount[config.countHTML ? "CharCountWithHTML" : "CharCount"];
  
  defaultFormat += charLabel + " %charCount%";
  if (config.maxCharCount > -1) {
    defaultFormat += "/" + config.maxCharCount;
  }
}
```

If we remove charLabel + from this code, the strange string of code is no longer displayed. I also choose to change the forward slash "/" to display the word *of* instead. I also put a single space to the left and right of the word *of*.

```javascript
if (config.ShowCharCount) {
  var charLabel = editor.lang.wordcount[config.countHTML ? "CharCountWithHTML" : "CharCount"];
  
  defaultFormat += " %charCount%";
  if (config.maxCharCount > -1) {
    defaultFormat += " of " + config.maxCharCount;
  }
}
```
![no strange characters](http://www.trojanbot.com/uploads/ckeditor_chili_fixed.png)

I have also attached a PDF which has a deeper dive into this issue.

[code changes to count characters.pdf](https://github.com/w8tcha/CKEditor-WordCount-Plugin/files/76772/code.changes.to.count.characters.pdf)

Thank you very much!
Jeremy

**Comment by martinezrw** [comment]
Alternatively if you want to do something without dealing with a build you can find the word count portion of the language js. In my case en.js. 

"wordcount":{"WordCount":"Words:","CharCount":"Characters:",**"CharCountWithHTML":" Space Used: "**,"Paragraphs":"Paragraphs:","pasteWarning":"Content can not be pasted because it is above the allowed limit","Selected":"Selected: ","title":"Statistics"}};

![spaceused](https://cloud.githubusercontent.com/assets/13893628/12635385/cceafebc-c53f-11e5-8418-e840e6c9a83a.jpg)
